AMS_N3 = 'ams_n3'
INFARCTS = 'infarcts'
INFILTRATE_LOCATION = 'infiltrate_location'
HISTOPATHOLOGY_REPORT = 'Some long report'
NVP = 'NVP'
POSITIVE = 'positive'
SINGLE_DOSE = 'single_dose'
VIBRIO = 'vibrio'
