from ambition_validators import DEVIATION, VIOLATION, TUBERCULOSIS
from ambition_validators import HEADACHE, VISUAL_LOSS
from ambition_visit_schedule import DAY1, DAY3, DAY5, DAY7, DAY14, DAY12, DAY10
from ambition_visit_schedule import WEEK16, WEEK10, WEEK8, WEEK6, WEEK4

BACTERIA = 'Bacteria'
CONTROL = 'control'
A2 = 'A'
AMS_N3 = 'AMS_N'
AMS_A4 = 'AMS_A'
CEREBRAL_OEDEMA = 'cerebral_oedema'
CONSENT_WITHDRAWAL = 'consent_withdrawn'
CXR_DESCRIPTION = 'Some cxr description'
DIFFUSE = 'diffuse'
FOCAL_NEUROLOGIC_DEFICIT = 'focal_neurologic_deficit'
INFARCTS = 'infarcts'
INFILTRATE_LOCATION = 'infiltrate_location'
HISTOPATHOLOGY_REPORT = 'Some long report'
N1 = 'N'
NEW_NEUROLOGY = 'new_neurology'
NVP = 'NVP'
POSITIVE = 'positive'
SINGLE_DOSE = 'single_dose'
THREE_DOSES = 'three_doses'
TWO_DOSES = 'three_doses'
VIBRIO = 'vibrio'
RESULTS_UNKNOWN = 'results_unknown'
ROUTINE_APPT = 'routine'
RECURRENCE_OF_SYMPTOMS_ACTION = 'submit-recurrence-symptoms'
STUDY_TERMINATION_CONCLUSION_ACTION = 'submit-study-termination-conclusion'
