from ambition_validators.constants import DEVIATION, VIOLATION


BACTERIA = 'Bacteria'
CONTROL = 'control'
A2 = 'A'
AMS_N3 = 'AMS_N'
AMS_A4 = 'AMS_A'
CEREBRAL_OEDEMA = 'cerebral_oedema'
CONSENT_WITHDRAWAL = 'withdrawal_of_subject_consent'
CXR_DESCRIPTION = 'Some cxr description'
DAY1 = '1000'
DAY3 = '1003'
DAY7 = '1007'
DAY14 = '1014'
DIFFUSE = 'diffuse'
FOCAL_NEUROLOGIC_DEFICIT = 'focal_neurologic_deficit'
INFARCTS = 'infarcts'
INFILTRATE_LOCATION = 'infiltrate_location'
HISTOPATHOLOGY_REPORT = 'Some long report'
N1 = 'N'
NEW_NEUROLOGY = 'new_neurology'
NVP = 'NVP'
POSITIVE = 'positive'
SINGLE_DOSE = 'single_dose'
THREE_DOSES = 'three_doses'
TWO_DOSES = 'three_doses'
VIBRIO = 'vibrio'
WEEK4 = '1028'
WEEK6 = '1042'
WEEK8 = '1056'
WEEK10 = '1070'
RANDOMIZED = 'RANDOMIZED'
