# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambition_subject', '0001_initial'),
        ('edc_appointment', '0007_auto_20170302_2220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_lab.Result'),
        ),
        migrations.AddField(
            model_name='historicalsubjectvisit',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_appointment.Appointment'),
        ),
        migrations.AddField(
            model_name='historicalsubjectvisit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresultitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresultitem',
            name='result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_lab.Result'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectvisit',
            unique_together=set([('subject_identifier', 'visit_schedule_name', 'schedule_name', 'visit_code'), ('subject_identifier', 'visit_schedule_name', 'schedule_name', 'report_datetime')]),
        ),
    ]
