# Generated by Django 2.0 on 2018-01-04 15:20

from django.db import migrations, models
import edc_consent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='consent_signature',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, null=True, validators=[edc_consent.validators.eligible_if_yes], verbose_name='I have verified that the participant has signed the consent form'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreconsent',
            name='consent_signature',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, null=True, validators=[edc_consent.validators.eligible_if_yes], verbose_name='I have verified that the participant has signed the consent form'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='consent_signature',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, null=True, validators=[edc_consent.validators.eligible_if_yes], verbose_name='I have verified that the participant has signed the consent form'),
        ),
        migrations.AlterField(
            model_name='subjectreconsent',
            name='consent_signature',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If no, participant is not eligible.', max_length=3, null=True, validators=[edc_consent.validators.eligible_if_yes], verbose_name='I have verified that the participant has signed the consent form'),
        ),
    ]
