# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model_fields.custom_fields
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeventfollowup',
            name='outcome',
            field=models.CharField(choices=[('Recovered', 'Recovered/Resolved'), ('Recovering', 'Recovering/Resolving at end of study'), ('Not Recovered', 'Not Recovered/Resolved at end of study'), ('Unknown', 'Unknown/Lost to follow-up'), ('Recovered with sequelae', 'Recovered with sequelae'), ('Death', 'Death')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalpatienthistory',
            name='neurological_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=250, null=True, verbose_name='...if "Other", specify'),
        ),
        migrations.AlterField(
            model_name='historicalradiology',
            name='date_ct_performed',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date CT performed'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='neurological_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=250, null=True, verbose_name='...if "Other", specify'),
        ),
        migrations.AlterField(
            model_name='radiology',
            name='date_ct_performed',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date CT performed'),
        ),
    ]
