# Generated by Django 2.0 on 2017-12-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='SubjectLocator',
        ),
        migrations.DeleteModel(
            name='HistoricalSubjectLocator',
        ),
    ]
