# Generated by Django 2.0.1 on 2018-01-17 07:55

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicallumbarpuncturecsf',
            name='csf_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='CSF Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicallumbarpuncturecsf',
            name='qc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='QC Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='lumbarpuncturecsf',
            name='csf_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='CSF Result Report Date and Time'),
        ),
        migrations.AlterField(
            model_name='lumbarpuncturecsf',
            name='qc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='QC Result Report Date and Time'),
        ),
    ]
