# Generated by Django 2.0.1 on 2018-01-05 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0002_auto_20180104_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmicrobiology',
            name='day_biopsy_taken',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='If positive, Study day positive culture sample taken'),
        ),
        migrations.AlterField(
            model_name='historicalmicrobiology',
            name='day_blood_taken',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='If positive, study day positive culture sample taken'),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='day_biopsy_taken',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='If positive, Study day positive culture sample taken'),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='day_blood_taken',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='If positive, study day positive culture sample taken'),
        ),
    ]
