# Generated by Django 2.0.1 on 2018-01-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0002_auto_20180117_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectrequisition',
            name='study_site',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectrequisition',
            name='study_site_name',
        ),
        migrations.RemoveField(
            model_name='subjectrequisition',
            name='study_site',
        ),
        migrations.RemoveField(
            model_name='subjectrequisition',
            name='study_site_name',
        ),
    ]
