# Generated by Django 2.0 on 2018-01-04 06:22

from django.db import migrations
import django_crypto_fields.fields.identity_field


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0002_auto_20180103_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='confirm_identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text='Retype the identity number (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Identity number'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='confirm_identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text='Retype the identity number (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='identity',
            field=django_crypto_fields.fields.identity_field.IdentityField(help_text=' (Encryption: RSA local)', max_length=71, verbose_name='Identity number'),
        ),
    ]
