# Generated by Django 2.0 on 2017-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0002_auto_20171227_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='action_identifier',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='action_identifier',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
