# Generated by Django 2.0 on 2017-12-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0003_auto_20171227_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='action_identifier',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='action_identifier',
        ),
    ]
