# Generated by Django 2.0 on 2018-01-04 07:03

from django.db import migrations, models
import django_crypto_fields.fields.lastname_field
import edc_consent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0004_auto_20180104_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'get_latest_by': 'consent_datetime', 'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is a minor.<BR>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's last and first name"),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='identity_type',
            field=models.CharField(max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='is_literate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No' provide witness's name on this form and signature on the paper document.", max_length=3, verbose_name='Is the participant literate?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ny', 'Chichewa'), ('en', 'English'), ('xh', 'isiXhosa'), ('lg', 'Luganda'), ('rny', 'Runyankore'), ('tn', 'Setswana'), ('sn', 'Shona')], help_text='The language used for the consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='legal_marriage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="If 'No', participant may not be consented.", max_length=3, null=True, verbose_name='If not a citizen, is the participant legally married to a Botswana citizen?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='marriage_certificate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="If 'No', participant may not be consented.", max_length=3, null=True, verbose_name='[Interviewer] Has the participant produced the marriage certificate as proof? '),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='witness_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is illiterate.<br>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Witness's last and first name"),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is a minor.<BR>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's last and first name"),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='identity_type',
            field=models.CharField(max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='is_literate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No' provide witness's name on this form and signature on the paper document.", max_length=3, verbose_name='Is the participant literate?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ny', 'Chichewa'), ('en', 'English'), ('xh', 'isiXhosa'), ('lg', 'Luganda'), ('rny', 'Runyankore'), ('tn', 'Setswana'), ('sn', 'Shona')], help_text='The language used for the consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='legal_marriage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="If 'No', participant may not be consented.", max_length=3, null=True, verbose_name='If not a citizen, is the participant legally married to a Botswana citizen?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='marriage_certificate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="If 'No', participant may not be consented.", max_length=3, null=True, verbose_name='[Interviewer] Has the participant produced the marriage certificate as proof? '),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='witness_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if participant is illiterate.<br>Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Witness's last and first name"),
        ),
    ]
