# Generated by Django 2.0.1 on 2018-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0004_auto_20180105_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='cd4_units',
            field=models.CharField(blank=True, choices=[('cells/mm^3', 'cells/mm^3')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='neutrophil_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='platelets_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='wbc_units',
            field=models.CharField(blank=True, choices=[('10^3/L', '10^3/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='cd4_units',
            field=models.CharField(blank=True, choices=[('cells/mm^3', 'cells/mm^3')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='neutrophil_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='platelets_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='wbc_units',
            field=models.CharField(blank=True, choices=[('10^3/L', '10^3/L')], max_length=10, null=True, verbose_name='units'),
        ),
    ]
