# Generated by Django 2.0 on 2017-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0004_auto_20171217_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpkpdcrf',
            name='ambisome_dose',
            field=models.IntegerField(help_text='Units in mg', null=True, verbose_name='Ambisome dose given'),
        ),
        migrations.AlterField(
            model_name='historicalpkpdcrf',
            name='fluconazole_dose_given',
            field=models.IntegerField(blank=True, help_text='Units in mg', null=True, verbose_name='What was the dose of Fluconazole given?'),
        ),
        migrations.AlterField(
            model_name='historicalpkpdcrf',
            name='flucytosine_dose',
            field=models.IntegerField(help_text='Units in mg', null=True, verbose_name='What was  the dose of Flucytosine given?'),
        ),
        migrations.AlterField(
            model_name='historicalprnmodel',
            name='chemistry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Blood chemistry requisitions, i.e ALT, Urea, Electrolytes and Creatinine', max_length=5, verbose_name='Chemistry?'),
        ),
        migrations.AlterField(
            model_name='pkpdcrf',
            name='ambisome_dose',
            field=models.IntegerField(help_text='Units in mg', null=True, verbose_name='Ambisome dose given'),
        ),
        migrations.AlterField(
            model_name='pkpdcrf',
            name='fluconazole_dose_given',
            field=models.IntegerField(blank=True, help_text='Units in mg', null=True, verbose_name='What was the dose of Fluconazole given?'),
        ),
        migrations.AlterField(
            model_name='pkpdcrf',
            name='flucytosine_dose',
            field=models.IntegerField(help_text='Units in mg', null=True, verbose_name='What was  the dose of Flucytosine given?'),
        ),
        migrations.AlterField(
            model_name='prnmodel',
            name='chemistry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Blood chemistry requisitions, i.e ALT, Urea, Electrolytes and Creatinine', max_length=5, verbose_name='Chemistry?'),
        ),
    ]
