# Generated by Django 2.0 on 2018-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0006_auto_20180104_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='completed_by_next_of_kin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='completed_by_next_of_kin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', editable=False, max_length=10),
        ),
    ]
