# Generated by Django 2.0.1 on 2018-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0006_auto_20180107_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprnmodel',
            name='blood_result',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Blood result?'),
        ),
        migrations.AlterField(
            model_name='historicalprnmodel',
            name='lumbar_puncture',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Lumbar puncture?'),
        ),
        migrations.AlterField(
            model_name='prnmodel',
            name='blood_result',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Blood result?'),
        ),
        migrations.AlterField(
            model_name='prnmodel',
            name='lumbar_puncture',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Lumbar puncture?'),
        ),
    ]
