# Generated by Django 2.0.1 on 2018-01-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0007_auto_20180108_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprnmodel',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprnmodel',
            name='subject_visit',
        ),
        migrations.RemoveField(
            model_name='prnmodel',
            name='subject_visit',
        ),
        migrations.DeleteModel(
            name='HistoricalPrnModel',
        ),
        migrations.DeleteModel(
            name='PrnModel',
        ),
    ]
