# Generated by Django 2.0.1 on 2018-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0008_auto_20180109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='wbc_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='wbc_units',
            field=models.CharField(blank=True, choices=[('10^9/L', '10^9/L')], max_length=10, null=True, verbose_name='units'),
        ),
    ]
