# Generated by Django 2.0.1 on 2018-01-10 10:08

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0009_auto_20180109_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectvisit',
            name='reason_missed_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=25, null=True, verbose_name='If "Other" reason for missed visit, specify'),
        ),
        migrations.AddField(
            model_name='subjectvisit',
            name='reason_missed_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=25, null=True, verbose_name='If "Other" reason for missed visit, specify'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='info_source_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If "Other" source of information, specify'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Not scheduled'), ('missed', 'Missed')], max_length=25, verbose_name='What is the reason for this visit report?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason_missed',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name="If 'Missed' above, provide the reason the scheduled visit was missed"),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason_unscheduled',
            field=models.CharField(choices=[('patient_unwell_outpatient', 'Patient unwell (outpatient)'), ('recurrence_symptoms', 'Recurrence of symptoms'), ('raised_icp_management', 'Raised ICP management'), ('art_initiation', 'ART initiation'), ('patient_hospitalised', 'Patient hospitalised'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name="If 'Unscheduled' above, provide reason for the unscheduled visit"),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason_unscheduled_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=25, null=True, verbose_name='If "Other" reason for unscheduled visit, specify'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='study_status',
            field=models.CharField(max_length=50, null=True, verbose_name="What is the participant's current study status"),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='info_source_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If "Other" source of information, specify'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Not scheduled'), ('missed', 'Missed')], max_length=25, verbose_name='What is the reason for this visit report?'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason_missed',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name="If 'Missed' above, provide the reason the scheduled visit was missed"),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason_unscheduled',
            field=models.CharField(choices=[('patient_unwell_outpatient', 'Patient unwell (outpatient)'), ('recurrence_symptoms', 'Recurrence of symptoms'), ('raised_icp_management', 'Raised ICP management'), ('art_initiation', 'ART initiation'), ('patient_hospitalised', 'Patient hospitalised'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name="If 'Unscheduled' above, provide reason for the unscheduled visit"),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason_unscheduled_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=25, null=True, verbose_name='If "Other" reason for unscheduled visit, specify'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='study_status',
            field=models.CharField(max_length=50, null=True, verbose_name="What is the participant's current study status"),
        ),
    ]
