# Generated by Django 2.0.1 on 2018-01-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0010_auto_20180110_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='cbc_requisition',
            field=models.ForeignKey(blank=True, help_text='Type the requisition identifier or select one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbc', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='cd4_requisition',
            field=models.ForeignKey(blank=True, help_text='Type the requisition identifier or select one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cd4', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='ft_requisition',
            field=models.ForeignKey(blank=True, help_text='Type the requisition identifier or select one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ft', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='vl_requisition',
            field=models.ForeignKey(blank=True, help_text='Type the requisition identifier or select one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vl', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='cbc_requisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ambition_subject.SubjectRequisition'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='cd4_requisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ambition_subject.SubjectRequisition'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='ft_requisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ambition_subject.SubjectRequisition'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='vl_requisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ambition_subject.SubjectRequisition'),
        ),
        migrations.AddField(
            model_name='historicalsubjectrequisition',
            name='subject_identifier',
            field=models.CharField(default='1', max_length=50, verbose_name='Subject Identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='subject_identifier',
            field=models.CharField(default='1', max_length=50, verbose_name='Subject Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpatienthistory',
            name='first_line_choice',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('EFV', 'EFV'), ('DTG', 'DTG'), ('NVP', 'NVP'), ('OTHER', 'Other')], default='N/A', max_length=5, verbose_name='If first line:'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='first_line_choice',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('EFV', 'EFV'), ('DTG', 'DTG'), ('NVP', 'NVP'), ('OTHER', 'Other')], default='N/A', max_length=5, verbose_name='If first line:'),
        ),
    ]
