# Generated by Django 2.0.1 on 2018-01-12 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0011_auto_20180112_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallumbarpuncturecsf',
            name='assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='historicallumbarpuncturecsf',
            name='requisition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ambition_subject.SubjectRequisition'),
        ),
        migrations.AddField(
            model_name='lumbarpuncturecsf',
            name='assay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assay Date and Time'),
        ),
        migrations.AddField(
            model_name='lumbarpuncturecsf',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='cbc_requisition',
            field=models.ForeignKey(blank=True, help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbc', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='cd4_requisition',
            field=models.ForeignKey(blank=True, help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cd4', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='ft_requisition',
            field=models.ForeignKey(blank=True, help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ft', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='vl_requisition',
            field=models.ForeignKey(blank=True, help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vl', to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='historicallumbarpuncturecsf',
            name='csf_wbc_cell_count',
            field=models.IntegerField(blank=True, help_text='acceptable units are mm<sup>3</sup>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Total CSF WBC cell count:'),
        ),
        migrations.AlterField(
            model_name='lumbarpuncturecsf',
            name='csf_wbc_cell_count',
            field=models.IntegerField(blank=True, help_text='acceptable units are mm<sup>3</sup>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Total CSF WBC cell count:'),
        ),
    ]
