# Generated by Django 2.0.1 on 2018-01-13 07:27

from django.db import migrations, models
import django.db.models.deletion
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0012_auto_20180112_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='cbc_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='cd4_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='ft_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='vl_assay_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='historicallumbarpuncturecsf',
            name='assay_datetime',
            field=models.DateTimeField(null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='lumbarpuncturecsf',
            name='assay_datetime',
            field=models.DateTimeField(null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Assay Date and Time'),
        ),
        migrations.AlterField(
            model_name='lumbarpuncturecsf',
            name='requisition',
            field=models.ForeignKey(help_text='Start typing the requisition identifier or select one from this visit', null=True, on_delete=django.db.models.deletion.PROTECT, to='ambition_subject.SubjectRequisition', verbose_name='Requisition'),
        ),
    ]
