# Generated by Django 2.0.1 on 2018-01-13 11:32

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0013_auto_20180113_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectrequisition',
            name='reason_not_drawn_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='reason_not_drawn_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectrequisition',
            name='reason_not_drawn',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('collection_failed', 'Tried, but unable to obtain sample from patient'), ('absent', 'Patient did not attend visit'), ('refused', 'Patient refused'), ('no_supplies', 'No supplies'), ('NOT_REQUIRED', 'No longer required for this visit'), ('OTHER', 'Other')], default='N/A', max_length=25, verbose_name='If not drawn, please explain'),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='reason_not_drawn',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('collection_failed', 'Tried, but unable to obtain sample from patient'), ('absent', 'Patient did not attend visit'), ('refused', 'Patient refused'), ('no_supplies', 'No supplies'), ('NOT_REQUIRED', 'No longer required for this visit'), ('OTHER', 'Other')], default='N/A', max_length=25, verbose_name='If not drawn, please explain'),
        ),
    ]
