# Generated by Django 2.0.1 on 2018-01-14 12:54

from django.db import migrations
from edc_consent.signals import requires_consent_on_pre_save
from django.db.models.signals import pre_save


def update_panel_fk(apps, schema_editor):
    pre_save.disconnect(
        receiver=requires_consent_on_pre_save,
        dispatch_uid='requires_consent_on_pre_save')
    Panel = apps.get_model('edc_lab.panel')
    SubjectRequisition = apps.get_model('ambition_subject.subjectrequisition')
    for obj in SubjectRequisition.objects.all():
        if not obj.panel:
            panel = Panel.objects.get(display_name=obj.panel_name)
            obj.panel = panel
            obj.save_base(update_fields=['panel'])


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0016_auto_20180114_1440'),
    ]

    operations = [
        migrations.RunPython(update_panel_fk),
    ]
