# Generated by Django 2.0.1 on 2018-01-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_lab', '0012_auto_20180114_1438'),
        ('ambition_subject', '0019_auto_20180115_0009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectrequisition',
            unique_together={('panel', 'subject_visit')},
        ),
    ]
